# Generated by Django 6.0.1 on 2026-01-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0002_alter_seller_id_alter_stripeaccount_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stripeaccount",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
