# Generated by Django 5.2.5 on 2026-01-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_consumerprofile_id_alter_sellerprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='Site owner/admin with full privileges'),
        ),
    ]
