# Generated by Django 6.0.1 on 2026-01-29 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profile_picture_alter_consumerprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_admin_email',
            field=models.BooleanField(default=True, help_text='Email notifications for admin actions'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_admin_inapp',
            field=models.BooleanField(default=True, help_text='Show in-app notifications for admin actions'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_orders_email',
            field=models.BooleanField(default=True, help_text='Email notifications for orders'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_orders_inapp',
            field=models.BooleanField(default=True, help_text='Show in-app notifications for orders'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_reviews_email',
            field=models.BooleanField(default=True, help_text='Email notifications for reviews'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_reviews_inapp',
            field=models.BooleanField(default=True, help_text='Show in-app notifications for reviews'),
        ),
        migrations.AlterField(
            model_name='consumerprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
