# Generated by Django 6.0.1 on 2026-01-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_address1_user_address2_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(blank=True, choices=[('', 'Use Site Default'), ('light', 'Light Mode'), ('dark', 'Dark Mode'), ('auto', 'Auto (System Preference)')], default='', help_text="User's theme preference.", max_length=10),
        ),
    ]
