# Generated by Django 6.0.1 on 2026-01-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_promobanner_fields'),
        ('accounts', '0008_user_theme_preference'),
    ]

    operations = [
    ]
