# Generated by Django 6.0.1 on 2026-01-29 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20260129_1341'),
        ('orders', '0003_alter_download_id_alter_lineitem_id_alter_order_id'),
        ('products', '0015_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='consumerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consumerprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='consumerprofile',
            name='download_history',
            field=models.ManyToManyField(blank=True, related_name='consumers', to='orders.download'),
        ),
        migrations.AddField(
            model_name='consumerprofile',
            name='favorite_categories',
            field=models.ManyToManyField(blank=True, related_name='favored_by_consumers', to='products.category'),
        ),
        migrations.AddField(
            model_name='consumerprofile',
            name='saved_searches',
            field=models.JSONField(blank=True, default=list, help_text='List of saved search queries'),
        ),
        migrations.AddField(
            model_name='consumerprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='Social media links'),
        ),
        migrations.AddField(
            model_name='consumerprofile',
            name='wishlist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.wishlist'),
        ),
    ]
