# Generated by Django 6.0.1 on 2026-01-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_consumerprofile_avatar_consumerprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerprofile',
            name='verified',
            field=models.BooleanField(default=False, help_text='Manually verified by staff'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='verified',
            field=models.BooleanField(default=False, help_text='Manually verified by staff'),
        ),
    ]
