# Generated by Django 6.0.1 on 2026-01-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_alter_dmca_id_alter_flag_id_alter_report_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('max_file_size_mb', models.PositiveIntegerField(default=20, help_text='Maximum upload file size in MB')),
                ('allowed_mime_types', models.TextField(default='application/sla,application/vnd.ms-pki.stl,application/octet-stream,image/jpeg,image/png', help_text='Comma-separated list of allowed MIME types')),
            ],
            options={
                'verbose_name': 'Security Setting',
                'verbose_name_plural': 'Security Settings',
            },
        ),
    ]
