# Generated by Django 5.2.5 on 2026-01-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_id_alter_license_id_alter_media_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_manual',
            field=models.BooleanField(default=False, help_text='Show as featured if checked'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_count',
            field=models.PositiveIntegerField(default=0, help_text='Auto-incremented on purchase'),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Auto-incremented on product view'),
        ),
    ]
