# Generated by Django 6.0.1 on 2026-01-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_id_alter_license_id_alter_media_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file_type',
            field=models.CharField(choices=[('stl', 'STL'), ('obj', 'OBJ'), ('3mf', '3MF'), ('zip', 'ZIP'), ('step', 'STEP'), ('iges', 'IGES'), ('jpg', 'JPG'), ('jpeg', 'JPEG'), ('png', 'PNG')], default='stl', max_length=10),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='product_files/'),
        ),
    ]
