# Generated by Django 6.0.1 on 2026-01-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_media_file_type_alter_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='draft',
            field=models.BooleanField(default=False, help_text='If checked, product is a draft and not visible to buyers.'),
        ),
    ]
