# Generated by Django 6.0.1 on 2026-01-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(blank=True, help_text='Stock for physical products. Leave blank for digital products.', null=True),
        ),
    ]
