# Generated by Django 6.0.1 on 2026-01-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional category image.', null=True, upload_to='category_images/'),
        ),
    ]
