# Generated by Django 6.0.1 on 2026-01-29 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_meta_description_product_meta_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Variant name (e.g., Size, Color, Material)', max_length=100)),
                ('value', models.CharField(help_text='Variant value (e.g., Large, Red, PLA)', max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional price override for this variant', max_digits=10, null=True)),
                ('inventory', models.IntegerField(blank=True, help_text='Stock for this variant (optional)', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'name', 'value')},
            },
        ),
    ]
