# Generated by Django 5.2.5 on 2026-01-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorefrontSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_products_mode', models.CharField(choices=[('manual', 'Manual (admin checkmark)'), ('most_viewed', 'Most Viewed'), ('most_purchased', 'Most Purchased')], default='manual', help_text='How to select featured products for the storefront.', max_length=20)),
            ],
            options={
                'verbose_name': 'Storefront Setting',
                'verbose_name_plural': 'Storefront Settings',
            },
        ),
    ]
