# Generated by Django 6.0.1 on 2026-01-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_alter_storefrontsettings_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefrontsettings',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('auto', 'Auto (System Preference)')], default='auto', help_text='Site theme: light, dark, or auto.', max_length=10),
        ),
    ]
