# Generated by Django 6.0.1 on 2026-01-29 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_tags'),
        ('sellers', '0004_sellerrating'),
        ('storefront', '0003_storefrontsettings_theme_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Order for display (lower = first)')),
                ('products', models.ManyToManyField(blank=True, to='products.product')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Show this creator as featured')),
                ('position', models.PositiveIntegerField(default=0, help_text='Order for display (lower = first)')),
                ('note', models.CharField(blank=True, help_text='Optional note or tagline', max_length=255)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sellers.seller')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
